# Generated by Django 2.2.3 on 2019-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Enter the name of the city to find out the weather in it.', max_length=30),
        ),
    ]
